### ISSUE TITLE
Wtyczka TVN player znowu nie działa. 

### ISSUE THREAD

**Issue by dani168** [pkontek/xbmc-pl-tv#11]
Wtyczka wywala błąd gdy próbuję ją uruchomić. Mam zainstalowany najnowszy Kodi 16, na Windows 7.

**Comment by skindzierm** [comment]
Witam,

Potwierdzam i zalaczam log: [http://pastebin.com/HPQVJb3E](url)
Bede wdzieczny za zarkniecie na problem.

Pozdrawiam.

**Comment by pkontek** [comment]
Niestety TVN zmieniło coś w API. Spróbuję namierzyć co się dzieje.

**Comment by skindzierm** [comment]
Witam,

zauwazylem poprawe :) Moge przegladac zawartosc TVNPlayer jednak przy probie odtwarzania wyskakuje blad. Zauwazylem rowniez, ze przy probie odtwarzania nie ma wyboru opcji HD.
Zalaczam [logi](http://pastebin.com/M6yickRN)
Nadmienie, ze kozystam z wlasnego proxy, ktore sprawdzielm i dziala.
Bede wdzieczny jesli moglbys zerknac.

Pozdrawiam.

**Comment by pkontek** [comment]
Poprawiłem pobieranie listy filmów (taki workarround), ale same filmy nadal nie działają. Będę nad tym jeszcze siedział, ale pewnie dopiero w weekend :(

**Comment by pkontek** [comment]
Naprawione w wersji 1.2.14 - przeszedłem na nowe API TVNPlayer.
