### ISSUE TITLE
Wtyczka TVN Player- problem z buforowaniem filmów

### ISSUE THREAD

**Issue by dani168** [pkontek/xbmc-pl-tv#12]
Wtyczka działa po ostatnim updacie, ale niestety przestaje buforować filmy po ok 9 sekundach. I jest tak z chyba wszystkimi pozycjami. Sprawdziłem ok. 10 różnych pozycji i wszędzie ten sam problem.

**Comment by pkontek** [comment]
Ups ... Popatrzę na to.

**Comment by skindzierm** [comment]
Chyba nie ma co sprawdzac ;-) z tego co wiem to zabezpieczenie DRM. Na ta chwile nie do przejscia.

Pozdrawiam.

**Comment by pkontek** [comment]
Tak to DRM. Widzę że wersja dla Androida nie ma zabezpieczeń DRM - niestety nie ma chyba jakości HD. Ale spróbuję przerobić plugin żeby wyświetlał w słabszej jakości, zawsze to lepsze niż nic :)

**Comment by skindzierm** [comment]
:-) w innej znanej wtyczce w opcjach można dokonać wyboru między Androidem
a Samsungiem TV. Przestawienie na Androida powoduje, ze wtyczka działa ale
jakość jak mówisz jest mocno średnia.

Pozdrawiam

**Comment by pkontek** [comment]
udało mi się tam gdzie mamy DRM przełączyć na Androida, w pozostałych przypadkach działa po staremu

**Comment by skindzierm** [comment]
Witam.
Wielkie dzieki ale jak to ma dzialac?
Kazdy material jaki odpalam ma wybor HD/SD i po 8s stop, wiec widac, ze to nadal DRM. Cos jest chyba nie halo.

Dzieki.

**Comment by pkontek** [comment]
Auć! Chyba coś za mało wrzuciłem :/

**Comment by pkontek** [comment]
Poprawiłem - daj znać czy działa.

**Comment by skindzierm** [comment]
Tak na szybko...chyba nadal jest coś nie tak. Teraz przy próbie odtwarzania
wyskakuje błąd. Wieczorem podesle logi.

Dzięki.
On 6 May 2016 07:32, "pkontek" <notifications@github.com> wrote:

Closed #12 <https://github.com/pkontek/xbmc-pl-tv/issues/12>.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/pkontek/xbmc-pl-tv/issues/12#event-652297851>

**Comment by skindzierm** [comment]
Witam,

[Obiecane logi](http://pastebin.com/8ZHxV7nB)

Dzieki.

**Comment by pkontek** [comment]
Sprawdź teraz.

**Comment by skindzierm** [comment]
Dziala wysmienicie. Bardzo dziekuje.

Pozdrowienia.
