### ISSUE TITLE
Tvn player

### ISSUE THREAD

**Issue by borys76** [pkontek/xbmc-pl-tv#13]
Witam
Tvn player dziala tylko przez proxy?
Dalo by Rade zrobic zeby dzialalo przez vpn?

**Comment by pkontek** [comment]
co do VPN to raczej trzeba skonfigurować poprawnie tunel w OS. Sam Kodi chyba nie ma tu nic do rzeczy

**Comment by mario75ne** [comment]
Po wejściu w menu na pierwszej stronie wtyczki TVN player, pierwsze 4 pozycje przy ikonie folderu brak nazwy. W następnej kategorii *Pogramy po próbie wejścia w tą kategorie wyrzuca informacje o błędzie dodatku.

**Comment by pkontek** [comment]
Pewnie zmieniło się API :/ 
Niestety nie mam teraz czasu zająć się tym tematem - jeśli chcesz się włączyć i naprawić błąd mogę Ci dać dostęp do repozytorium.
