### ISSUE TITLE
TVNplayer odtwarza tylko kilka sekund.

### ISSUE THREAD

**Issue by skindzierm** [pkontek/xbmc-pl-tv#15]
Witam,

tak jak w temacie. Dzieje sie tak na jakosci Wysokiej i Niskiej.
Bardzo bym prosil w miare mozliwosci o zerknie na problem. Moze udaloby sie cos z tym zrobic.
**[Logi](http://pastebin.com/jmDhNTGr)**
Dziekuje.

**Comment by pkontek** [comment]
Naprawione w wersji 1.3.5

**Comment by skindzierm** [comment]
Witam,
ponownie ten sam problem :-/ Czy jest jakas szansa na naprawe? 
Jesli potrzeba moge pozniej podeslac logi.

Dziekuje.

**Comment by pkontek** [comment]
Poprawione w wersji 1.3.6 - do tego mamy znowu HD :)
Jeśli coś nie będzie działać napisz dla jakiego konkretnie filmu masz problem.
