### ISSUE TITLE
vod.tvp.pl - problem

### ISSUE THREAD

**Issue by skindzierm** [pkontek/xbmc-pl-tv#5]
Witam,

zauazylem, ze pojawil sie problem z odtwarzaniem na pluginie vod.tvp.pl "one ore more items failed to play". Nie jestem pewien czy to tylko u mnie. Kozystam z proxy ale TVN plugin z tym samym proxy dziala bez problemow.
Logs: http://pastebin.com/GvV4QThV
Czy jest jakas szansa by to naprawic?
Dziekuje i Pozdrawiam.
M.

**Comment by pkontek** [comment]
Problem jest na jakimś konkretnym filmie czy na wszysktich?

Co do filmu z logów. spróbuj w przeglądarce internetowej odtworzyć:
http://46.28.242.11/token/video/vod/19194869/20150329/1486625431/29255e95-a206-4a8f-aaae-9962ca601cbb/video-7.mp4
Jeśli zadziała w przeglądarce z proxy to znaczy nie jest to problem z proxy, ale podejrzewam że jednak jest...

**Comment by skindzierm** [comment]
Witam,

okazuje sie, ze problem nie jest z proxy. Wydaje mi sie, ze TVP calkowicie zablokowala dostep to swoich IP z poza PL. Nawet nie ma mozliwosci wykonac ping do 46.28.242.12 czy 46.28.242.11 gdzie TVP trzyma materialy Video (sprawdzone z UK i z DE). Moze jest to jakis wiekszy problem z routing'iem (mam taka nadzieje) w co jednak watpie.
Jako, ze wtyczka wyciaga tylko sam link kozystajac z proxy, nie ma mozliwosci ogladania Video. Przez przgladarke z proxy, swiezo wygenerowany link dziala bez problemow.

**Comment by pkontek** [comment]
Hmmm - skoro w przeglądarce działa. powinno działać w XBMC. Czy na pewno ustawiłeś proxy w ustawieniach wtyczki?
Bo z logów nie widzę, żeby łączył się przez proxy ale w logach chyba się to nie loguje :/

Możesz podesłać swój settings.xml z katalogu userdata/addon_data/plugin.video.pl-tv.vod.tvp.pl ?

**Comment by skindzierm** [comment]
Proxy mam na 100% ustawione.
Standardowo wtyczka przez proxy wyciaga tylko adres z plikiem video (i to dziala jak widac w logach.adress jest pobierany prawidlowo) a juz sam stream leci bezposrednio z serv TVP, a nie przez proxy (i tu jest problem, poniewaz TVP chyba zablokowalo dostep do tych serwerow z poza PL lub jest jakis wiekszy problem).
W przegladarce z proxy dziala wszystko poniewaz tak jak i adres jest pobieranych przez proxy, tak samo i strumien video.

**Comment by pkontek** [comment]
zrobiłem poprawkę - wygląda na to, że strumień rzeczywiście nie był ładowany przez proxy.
Możesz zweryfikować czy działa? Trzeba ręcznie zastąpić plik default.py w katalogu wtyczki tym poniżej:
https://raw.githubusercontent.com/pkontek/xbmc-pl-tv/master/plugin.video.pl-tv.vod.tvp.pl/default.py

**Comment by skindzierm** [comment]
Wlasnie sprawdzilem TVP przez proxy i okazuje sie, ze TVP chyba cos miesza ze swoimi adresami IP.
Wczoraj nic nie bylo dostepne z UK. To co sprawdzalem serwowane bylo z IP 46.28....itd. Teraz okazuje sie, ze czesc materialu (ktory sprawdzalem wczoraj) juz leci z nowych IP 195.245.... i nie ma zadnego problemu z dostepem z poza PL. Po wyciagnieciu linka do Video przez PL proxy, link ten bez problemu dziala w UK bez uzycia proxy (i mozna ogladac juz bez proxy). 
Czy mozemy wstrzymac sie z jakimikolwiek zmianami na kilka dni? Zobaczymy jak sprawa sie rozwinie.
Wychodzi na to, ze problem nie leza ani po stronie wtyczki ani po stronie mojego proxy.
Mam nadzieje, ze TVP naprawi cos tam u siebie i wszystko bedzie smigac tak jak wczesniej. Streamowanie calego Video przez proxy nie bedzie raczej dobrym wyborem, bo tak jak ja, zapewne wiele osob ma proxy na domowym necie gdzie Upload to pewno max 1Mb/s. :-/
Dziekuje.

**Comment by pkontek** [comment]
Ok poczekajmy

**Comment by pkontek** [comment]
Choć wydaje mi się, że moja zmiana powinna pomóc, bo teraz będzie to działać tak jak dla TVN.

**Comment by skindzierm** [comment]
Pomoc pomoze ale z 1Mb/s uploadem mojego PL proxy nie da sie nic obejzec (bedzie buforowac przy lepszej jakosci co pare s.). 
Na 99% jestem pewny, ze we wszystkich wtyczkach tylko adres jest wyciagany, a stream Video leci juz bezposrednio od nadawcy.

**Comment by skindzierm** [comment]
No to chyba robi sie co raz gozej. Teraz w 90% mam script failed - error. Czy jest jakas szansa by to poprawic? 
http://pastebin.com/Km2ki3PN

Dziekuje i Pozdrawiam.

**Comment by skindzierm** [comment]
Witam,

jest chyba coraz gorzej. Teraz w 90% przypadkow jest script failed - error. Zalaczam log.
http://pastebin.com/r42zbrUq
Czy istnieje jakas szansa by to naprawic?

Dziekuje i Pozdrawiam.

**Comment by pkontek** [comment]
Popatrzę na to po świętach

**Comment by pkontek** [comment]
Wygląda na to, że nie wszystko szło przez proxy.
Zmodyfikowałem skrypt, tak żeby wszystkie rzeczy poza samym streamem pobierał przez proxy. Możesz pobrać najnowszy default.py i przetestować?

**Comment by skindzierm** [comment]
Super. Sprawa calego menu i przegladania zawartosci VOD.TVP dziala jak trzeba.
Nadal pozostal problem ze streamami z puli IP 46.28.x.x ale chyba tak na razie zostanie. Wyglada na to, ze tylko najnowsze materialy (ostatni lub dwa ostatne odcinki) leca z tej puli a pozniej juz z tej drugiej dzialajacej.

Serdecznie dziekuje i bede obserwowal co dalej z tymi streamami.
