### ISSUE TITLE
wtyczka vod.tvp.pl- nie działa żaden materiał video

### ISSUE THREAD

**Issue by dani168** [pkontek/xbmc-pl-tv#6]
Wtyczkę mogę normalnie uruchomić, wybrać kategorię i konkretne video. Niestety po wybraniu konkretnego materiału pojawia się na ułamek sekundy "klepsydra" i nic się nie dzieje. Nawet nie ma komunikatu o błędzie. 
Mam Win xp, xbmc 12.3 FRODO.i wtyczkę vod.tvp.pl w wersji 1.0.12

**Comment by pkontek** [comment]
Dziwna sprawa, bo działać przestało ale nie wszystkim (u mnie np. działa bez problemów).
Będę to sprawdzał - i tak zamierzałem przepisać trochę wtyczkę, więc może będzie to dobra okazja :)

**Comment by dani168** [comment]
Bardzo dziękuję za odpowiedź i zainteresowanie się tematem. Pozdrawiam i czekam na efekty. :)

**Comment by pkontek** [comment]
Poprawione - w wersji 1.0.13

**Comment by dani168** [comment]
No i teraz wszystko pięknie śmiga! Bardzo dziękuję za szybkie zajęcie się problemem. Pozdrawiam :)
