### ISSUE TITLE
wtyczka tvnplayer odtwarza niektóre filmy z najniższej jakości

### ISSUE THREAD

**Issue by dani168** [pkontek/xbmc-pl-tv#7]
Niektóre filmy są odtwarzane w najniższej jakości.
Mam Win xp, xbmc 12.3 FRODO i wtyczkę tvnplayer w wersji 2.0.0.

**Comment by pkontek** [comment]
Czy w opcjach ustawiałeś jakość domyślną? możesz podać które konkretnie?

**Comment by dani168** [comment]
Próbowałem i tak i tak. Jeśli chodzi o konkretny film to np. Betlejewski prowokacjen sezon 2n odcinek 2.

**Comment by pkontek** [comment]
Hmm. nie ma już tego odcinka na liście a odcinek 3 wyświetla się u mnie w 720p. 
Możesz sprawdzić jak jest u Ciebie? może to TVN coś skiepścił z tym filmem? Może jakiś inny przykład?

**Comment by dani168** [comment]
Może rzeczywiście wina leżała po stronie TVNu. Problem pojawił się nagle i wygląda na to, że w ciągu tygodnia zniknął. Znalazłem Kuba Wojewódzki talk show ciąg dalszy- Sarsa i Pascal Brodnicki, który odwiera się w jakości średniej i ten sam odcinek w pełnej wersji, ale jest to odcinek sprzed kilku tygodni. Kolejne już śmigają w HD. Wygląda na to, że problem naprawił się samoczynnie. :)

**Comment by pkontek** [comment]
OK w takim razie zamykam zgłoszenie. Jeśli będą dalsze problem proszę o kontakt ;)
